DROP TABLE VISITS CASCADE;
DROP TABLE AUTOREPAIR_SERVICES CASCADE;
DROP TABLE SERVICES CASCADE;
DROP TABLE CLIENTS CASCADE;
DROP TABLE CATEGORY_SERVICES CASCADE;
DROP TABLE CARS CASCADE;
DROP TABLE AUTOREPAIRS CASCADE;
DROP TABLE schedule_workings CASCADE;
DROP TABLE specialization_autorepairs CASCADE;
DROP TABLE visit_serviceS CASCADE;
DROP TABLE specializations CASCADE;


select * from clients
select * from visits
select * from cars
select * from autorepair_services
select * from Visit_Services


Delete from Clients where name = '6456'

Update Visits set is_completed = true

CREATE TABLE Clients (
    client_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL DEFAULT 'UNKNOWN',
    surname VARCHAR(255),
    middlename VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    login VARCHAR(100) UNIQUE,
    password VARCHAR(255),
	CONSTRAINT UQ_CLIENT_NAME_EMAIL UNIQUE(name, email)
);


CREATE TABLE Cars (
    car_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    brand VARCHAR(100),
    model VARCHAR(100),
    engine_type VARCHAR(50),
    year INTEGER,
	insurance TIMESTAMP,
    license_plate VARCHAR(15) NOT NULL UNIQUE,
    vin VARCHAR(50) NOT NULL UNIQUE,
    client_id INTEGER NOT NULL,
    FOREIGN KEY (client_id) REFERENCES Clients(client_id) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE Autorepairs (
    autorepair_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    description TEXT,
    adress TEXT,
    index VARCHAR(20),
    workers_amount INTEGER DEFAULT 1 CHECK (workers_amount > 0),
    phone VARCHAR(50),
    email VARCHAR(255),
    ranking DECIMAL(3,2) DEFAULT 0.00 CHECK (ranking >= 0 AND ranking <= 5),
    password VARCHAR(100)
);


CREATE TABLE Visits (
    visit_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_time TIMESTAMP,
    alternative_date_time TIMESTAMP CHECK (alternative_date_time > date_time),
    note TEXT,
    payment_way VARCHAR(10) DEFAULT 'готівка' CHECK (payment_way IN ('готівка', 'картка')),
    payment_status VARCHAR(15) DEFAULT 'не оплачено' CHECK (payment_status IN ('оплачено', 'не оплачено')),
    is_completed BOOLEAN DEFAULT FALSE, 
    is_urgent BOOLEAN DEFAULT FALSE, 
    car_id INTEGER NOT NULL,
    autorepair_id INTEGER,
    FOREIGN KEY (car_id) REFERENCES Cars(car_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (autorepair_id) REFERENCES Autorepairs(autorepair_id) ON DELETE SET NULL ON UPDATE CASCADE
);


CREATE TABLE Category_Services (
    category_service_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_name VARCHAR(255) NOT NULL
);


CREATE TABLE Services (
    service_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    category_services_id INTEGER,
    FOREIGN KEY (category_services_id) REFERENCES Category_Services(category_service_id) ON DELETE SET NULL ON UPDATE CASCADE
);



CREATE TABLE Autorepair_Services (
    autorepair_service_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    autorepair_id INTEGER NOT NULL REFERENCES Autorepairs(autorepair_id) ON DELETE CASCADE ON UPDATE CASCADE,
    service_id INTEGER NOT NULL REFERENCES Services(service_id) ON DELETE RESTRICT ON UPDATE CASCADE,
    service_price DECIMAL(10,2) NOT NULL CHECK(service_price > 0),
    garantie_term INTEGER DEFAULT 0 CHECK(garantie_term > 0),
	duration INTEGER NOT NULL CHECK(duration > 0)
);


CREATE TABLE Specializations (
    specialtion_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL
);


CREATE TABLE Visit_Services (
    visit_service_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    problem_description TEXT,
    visit_id INTEGER NOT NULL,
    autorepair_service_id INTEGER,
    FOREIGN KEY (visit_id) REFERENCES Visits(visit_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (autorepair_service_id) REFERENCES Autorepair_Services(autorepair_service_id) ON DELETE RESTRICT ON UPDATE CASCADE
);


CREATE TABLE Schedule_Workings (
    schedule_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    day_of_week VARCHAR(2) NOT NULL CHECK (day_of_week IN ('Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Нд')),
    start_time_working TIME DEFAULT '08:00',
    end_time_working TIME DEFAULT '18:00',
    comment TEXT,
    autorepair_id INTEGER NOT NULL,
    FOREIGN KEY (autorepair_id) REFERENCES Autorepairs(autorepair_id) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE Specialization_Autorepairs (
    specialtion_autorepair_id SERIAL PRIMARY KEY NOT NULL,
    model VARCHAR(100),
    engine_type VARCHAR(50),
    year INTEGER,
    autorepair_id INTEGER NOT NULL,
    specialtion_id INTEGER NOT NULL,
    FOREIGN KEY (autorepair_id) REFERENCES Autorepairs(autorepair_id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (specialtion_id) REFERENCES Specializations(specialtion_id) ON DELETE CASCADE ON UPDATE CASCADE
);



---------------------------------------------------------------------------------------------------------------------
CREATE INDEX IDX_CARS_CLIENT ON CARS(CLIENT_ID);
CREATE INDEX IDX_VISITS_CAR ON VISITS(CAR_ID);
CREATE INDEX IDX_ARS_AUTOREPAIR ON Autorepair_Services(autorepair_id);
CREATE INDEX idx_vs_visit ON Visit_Services(visit_id);
CREATE INDEX IDX_VISIT_SERVICE_AUTOREPAIR_SERVICE ON Visit_Services(autorepair_service_id);
---------------------------------------------------------------------------------------------------------------------


INSERT INTO Autorepairs (name, description, adress, index, workers_amount, phone, email, ranking, password) VALUES
('AutoMaster Київ', 'Повний спектр авторемонтних робіт', 'м. Київ, вул. Хрещатик 22', '01001', 12, '+380501112233', 'info@automaster.ua', 4.7, 'pass123'),
('MegaService Львів', 'Сучасна СТО з професійним обладнанням', 'м. Львів, вул. Зелена 15', '79000', 9, '+380671234567', 'office@megaservice.ua', 4.5, 'qwe891'),
('DriveFix Одеса', 'Швидкий сервіс та ремонт', 'м. Одеса, вул. Арнаутська 44', '65000', 7, '+380931112244', 'contact@drivefix.ua', 4.3, 'fixit321'),
('TechGarage Дніпро', 'Професійна діагностика і ремонт', 'м. Дніпро, пр. Яворницького 101', '49000', 14, '+380991234987', 'support@techgarage.ua', 4.8, 'secure999'),
('MotorPro Харків', 'Ремонт двигунів та КПП', 'м. Харків, вул. Сумська 9', '61000', 11, '+380503334455', 'help@motorpro.ua', 4.6, 'motor555'),
('PitStop Полтава', 'Швидкі послуги по ТО', 'м. Полтава, вул. Європейська 12', '36000', 6, '+380506667788', 'pitstop@sto.ua', 4.2, 'ps111'),
('AutoLine Чернігів', 'Сервіс та ремонт підвіски', 'м. Чернігів, вул. Реміснича 7', '14000', 8, '+380632221100', 'shop@autoline.ua', 4.4, 'line222'),
('CarFix Вінниця', 'Комплексний ремонт автомобілів', 'м. Вінниця, вул. Соборна 55', '21000', 10, '+380987776655', 'service@carfix.ua', 4.6, 'vnn123'),
('ProGarage Житомир', 'Електрика та складні ремонти', 'м. Житомир, вул. Київська 34', '10001', 9, '+380931234100', 'admin@progarage.ua', 4.7, 'pg777'),
('RepairHub Рівне', 'Гарантійний професійний ремонт', 'м. Рівне, вул. Чорновола 18', '33000', 5, '+380671994455', 'hub@repair.ua', 4.1, 'rh999');



INSERT INTO Category_Services (category_name) VALUES 
('Діагностика'), ('Технічне обслуговування'), ('Ремонт ходової частини'), ('Ремонт двигуна'), 
('Електрика та електроніка'), ('Шиномонтаж та балансування'), ('Трансмісія та коробка передач');


INSERT INTO Services (name, description, category_services_id)
VALUES 
('Компʼютерна діагностика', 'Діагностика електронних систем автомобіля за допомогою OBD-II сканера', 1),

('Діагностика підвіски', 'Перевірка стану амортизаторів, сайлентблоків, шарових опор та стабілізаторів', 1),

('Заміна масла та фільтрів', 'Комплексна заміна моторного масла, масляного та повітряного фільтра', 2),

('Заміна гальмівних колодок', 'Передні або задні колодки із перевіркою стану дисків', 2),

('Ремонт амортизаторів', 'Заміна передніх та задніх амортизаторів з подальшою перевіркою розвалу', 3),

('Заміна кульової опори', 'Демонтаж та встановлення нової кульової опори передньої підвіски', 3),

('Капітальний ремонт двигуна', 'Повний розбір, дефектовка та заміна зношених компонентів двигуна', 4),

('Заміна ГРМ', 'Заміна ременя ГРМ, роликів та натягувача, перевірка фаз газорозподілу', 4),

('Діагностика електрики', 'Перевірка роботи генератора, акумулятора, стартеру та електропроводки', 5),

('Ремонт генератора', 'Заміна щіток, підшипників та діодного моста генератора', 5),

('Монтаж та балансування шин', 'Зняття та встановлення шин, балансування коліс на стенді', 6),

('Ремонт проколу шини', 'Латка або грибок залежно від місця пошкодження', 6),

('Ремонт коробки передач', 'Діагностика та повний ремонт механічної КПП', 7),

('Заміна зчеплення', 'Демонтаж та встановлення комплекту зчеплення: корзина, диск, вижимний', 7),

('Заміна масла в КПП', 'Повна заміна трансмісійного масла у механічній або автоматичній коробці', 7);




-- ================================
-- 1. AutoMaster Київ (id = 1)
-- ================================
INSERT INTO Autorepair_Services (autorepair_id, service_id, service_price, garantie_term, duration) VALUES
(1, 1, 600, 30, 40),
(1, 3, 950, 20, 90),
(1, 4, 700, 25, 60),
(1, 5, 2200, 60, 180),
(1, 9, 850, 30, 50),
(1, 11, 500, 10, 30);


-- ================================
-- 2. MegaService Львів (id = 2)
-- ================================
INSERT INTO Autorepair_Services (autorepair_id, service_id, service_price, garantie_term, duration) VALUES
(3, 1, 550, 20, 40),
(3, 3, 880, 15, 85),
(3, 4, 690, 20, 55),
(3, 9, 780, 25, 45),
(3, 12, 320, 5, 20);


-- ================================
-- 3. DriveFix Одеса (id = 3)
-- ================================
INSERT INTO Autorepair_Services (autorepair_id, service_id, service_price, garantie_term, duration) VALUES
(3, 1, 550, 20, 40),
(3, 3, 880, 15, 85),
(3, 4, 690, 20, 55),
(3, 9, 780, 25, 45),
(3, 12, 320, 5, 20);


-- ================================
-- 4. TechGarage Дніпро (id = 4)
-- ================================
INSERT INTO Autorepair_Services (autorepair_id, service_id, service_price, garantie_term, duration) VALUES
(4, 1, 620, 30, 40),
(4, 2, 470, 20, 45),
(4, 7, 4800, 150, 240),
(4, 8, 2100, 70, 180),
(4, 9, 900, 35, 50),
(4, 13, 5200, 160, 250),
(4, 15, 1100, 25, 70);


-- ================================
-- 5. MotorPro Харків (id = 5)
-- ================================
INSERT INTO Autorepair_Services (autorepair_id, service_id, service_price, garantie_term, duration) VALUES
(5, 7, 5000, 150, 230),
(5, 8, 2300, 60, 160),
(5, 13, 5400, 170, 260),
(5, 15, 1050, 30, 70);

-- ================================
-- 6. PitStop Полтава (id = 6)
-- ================================
INSERT INTO Autorepair_Services (autorepair_id, service_id, service_price, garantie_term, duration) VALUES
(6, 3, 780, 15, 75),
(6, 4, 700, 20, 55),
(6, 11, 450, 10, 25),
(6, 12, 300, 5, 20);


-- ================================
-- 7. AutoLine Чернігів (id = 7)
-- ================================
INSERT INTO Autorepair_Services (autorepair_id, service_id, service_price, garantie_term, duration) VALUES
(7, 2, 420, 12, 40),
(7, 5, 2100, 50, 170),
(7, 6, 1600, 45, 120),
(7, 9, 820, 25, 50),
(7, 11, 470, 10, 30);


-- ================================
-- 8. CarFix Вінниця (id = 8)
-- ================================
INSERT INTO Autorepair_Services (autorepair_id, service_id, service_price, garantie_term, duration) VALUES
(8, 1, 600, 25, 40),
(8, 3, 920, 20, 85),
(8, 5, 2000, 55, 150),
(8, 10, 950, 35, 60),
(8, 14, 2600, 80, 200);


-- ================================
-- 9. ProGarage Житомир (id = 9)
-- ================================
INSERT INTO Autorepair_Services (autorepair_id, service_id, service_price, garantie_term, duration) VALUES
(9, 1, 620, 30, 40),
(9, 9, 930, 40, 55),
(9, 10, 1100, 40, 60),
(9, 13, 5100, 150, 240),
(9, 14, 2500, 75, 180);


-- ================================
-- 10. RepairHub Рівне (id = 10)
-- ================================
INSERT INTO Autorepair_Services (autorepair_id, service_id, service_price, garantie_term, duration) VALUES
(10, 3, 850, 20, 80),
(10, 4, 690, 18, 55),
(10, 11, 430, 10, 25),
(10, 12, 320, 5, 20),
(10, 1, 580, 20, 40);



INSERT INTO Schedule_Workings (day_of_week, start_time_working, end_time_working, comment, autorepair_id) VALUES

-- AutoMaster Київ (1) — стандартний графік, неділя коротка
('Пн', '08:00', '18:00', NULL, 1),
('Вт', '08:00', '18:00', NULL, 1),
('Ср', '08:00', '18:00', NULL, 1),
('Чт', '08:00', '18:00', NULL, 1),
('Пт', '08:00', '17:00', 'скорочений день', 1),
('Сб', '09:00', '15:00', 'робота за попереднім записом', 1),
('Нд', '10:00', '14:00', 'короткий день', 1),

-- MegaService Львів (2) — відкриваються раніше, неділя вихідна
('Пн', '07:00', '17:00', NULL, 2),
('Вт', '07:00', '17:00', NULL, 2),
('Ср', '07:00', '17:00', NULL, 2),
('Чт', '07:00', '17:00', NULL, 2),
('Пт', '07:00', '16:00', 'санітарна година о 15:00', 2),
('Сб', '08:00', '14:00', NULL, 2),

-- DriveFix Одеса (3) — пізній старт, довго працюють
('Пн', '09:00', '19:00', NULL, 3),
('Вт', '09:00', '19:00', NULL, 3),
('Ср', '09:00', '19:00', NULL, 3),
('Чт', '09:00', '20:00', 'подовжений день', 3),
('Пт', '09:00', '18:00', NULL, 3),
('Сб', '10:00', '16:00', NULL, 3),
('Нд', '10:00', '15:00', 'лише діагностика', 3),

-- TechGarage Дніпро (4) — два неробочих дні
('Пн', '08:00', '18:00', NULL, 4),
('Вт', '08:00', '18:00', NULL, 4),
('Ср', '08:00', '18:00', NULL, 4),
('Чт', '08:00', '18:00', NULL, 4),
('Пт', '08:00', '18:00', NULL, 4),

-- MotorPro Харків (5) — змінний графік
('Пн', '07:30', '17:00', NULL, 5),
('Вт', '07:30', '17:00', NULL, 5),
('Ср', '08:00', '18:00', 'зміна бригади', 5),
('Чт', '08:00', '18:00', NULL, 5),
('Пт', '08:00', '16:00', 'скорочений день', 5),
('Сб', '09:00', '14:00', NULL, 5),

-- PitStop Полтава (6) — працюють навіть у неділю повний день
('Пн', '08:00', '18:00', NULL, 6),
('Вт', '08:00', '18:00', NULL, 6),
('Ср', '08:00', '18:00', NULL, 6),
('Чт', '08:00', '18:00', NULL, 6),
('Пт', '08:00', '18:00', NULL, 6),
('Сб', '08:00', '16:00', NULL, 6),
('Нд', '09:00', '17:00', 'підвищене навантаження', 6),

-- AutoLine Чернігів (7)
('Пн', '08:00', '17:00', NULL, 7),
('Вт', '08:00', '17:00', NULL, 7),
('Ср', '08:00', '17:00', NULL, 7),
('Чт', '09:00', '18:00', 'зміщений графік', 7),
('Пт', '09:00', '18:00', NULL, 7),
('Сб', '10:00', '15:00', NULL, 7),

-- CarFix Вінниця (8) — найширший графік
('Пн', '07:00', '19:00', NULL, 8),
('Вт', '07:00', '19:00', NULL, 8),
('Ср', '07:00', '19:00', NULL, 8),
('Чт', '07:00', '19:00', NULL, 8),
('Пт', '07:00', '17:00', NULL, 8),
('Сб', '08:00', '16:00', NULL, 8),
('Нд', '09:00', '14:00', 'короткий день', 8),

-- ProGarage Житомир (9)
('Пн', '08:30', '18:00', NULL, 9),
('Вт', '08:30', '18:00', NULL, 9),
('Ср', '08:30', '18:00', NULL, 9),
('Чт', '08:30', '18:00', NULL, 9),
('Пт', '08:30', '17:00', 'санітарна година', 9),
('Сб', '09:00', '14:00', NULL, 9),

-- RepairHub Рівне (10) — субота неробоча
('Пн', '08:00', '18:00', NULL, 10),
('Вт', '08:00', '18:00', NULL, 10),
('Ср', '08:00', '18:00', NULL, 10),
('Чт', '08:00', '18:00', NULL, 10),
('Пт', '08:00', '18:00', NULL, 10),
('Нд', '10:00', '15:00', NULL, 10);


INSERT INTO Specializations (NAME) VALUES
('Toyota'), ('Suzuki'), ('Audi'), ('BMW'), ('Ford'), ('Jaguar'), ('Acura'), ('Mercedes-Benz');


-- Київ: AutoMaster
INSERT INTO Specialization_Autorepairs 
(model, engine_type, year, autorepair_id, specialtion_id) VALUES
('Camry', 'Бензин', 2018, 1, 1),
('X5', 'Дизель', 2019, 1, 4),
('XF', 'Бензин', 2020, 1, 6);

-- Львів: MegaService
INSERT INTO Specialization_Autorepairs 
(model, engine_type, year, autorepair_id, specialtion_id) VALUES
('Vitara', 'Бензин', 2017, 2, 2),
('A6', 'Дизель', 2019, 2, 3),
('MDX', 'Бензин', 2018, 2, 7),
('E-Class', 'Дизель', 2020, 2, 8);

-- Одеса: DriveFix
INSERT INTO Specialization_Autorepairs 
(model, engine_type, year, autorepair_id, specialtion_id) VALUES
('Focus', 'Бензин', 2016, 3, 5),
('Corolla', 'Гібрид', 2021, 3, 1);


-- Дніпро: TechGarage
INSERT INTO Specialization_Autorepairs 
(model, engine_type, year, autorepair_id, specialtion_id) VALUES
('3 Series', 'Бензин', 2018, 4, 4),
('C-Class', 'Дизель', 2019, 4, 8),
('SX4', 'Бензин', 2017, 4, 2);


-- Харків: MotorPro
INSERT INTO Specialization_Autorepairs 
(model, engine_type, year, autorepair_id, specialtion_id) VALUES
('F-Pace', 'Дизель', 2020, 5, 6),
('Q7', 'Дизель', 2018, 5, 3),
('Camry', 'Бензин', 2019, 5, 1),
('Land Cruiser', 'Дизель', 2019, 5, 1);


-- Полтава: PitStop
INSERT INTO Specialization_Autorepairs 
(model, engine_type, year, autorepair_id, specialtion_id) VALUES
('RDX', 'Бензин', 2017, 6, 7),
('Mondeo', 'Дизель', 2016, 6, 5);

-- Чернігів: AutoLine
INSERT INTO Specialization_Autorepairs 
(model, engine_type, year, autorepair_id, specialtion_id) VALUES
('GLC', 'Дизель', 2019, 7, 8),
('Swift', 'Бензин', 2015, 7, 2),
('XE', 'Бензин', 2018, 7, 6);


-- Вінниця: CarFix
INSERT INTO Specialization_Autorepairs 
(model, engine_type, year, autorepair_id, specialtion_id) VALUES
('A4', 'Бензин', 2017, 8, 3),
('5 Series', 'Дизель', 2019, 8, 4);


-- Житомир: ProGarage
INSERT INTO Specialization_Autorepairs 
(model, engine_type, year, autorepair_id, specialtion_id) VALUES
('RAV4', 'Гібрид', 2020, 9, 1),
('TLX', 'Бензин', 2018, 9, 7),
('Kuga', 'Дизель', 2019, 9, 5);


-- Рівне: RepairHub
INSERT INTO Specialization_Autorepairs 
(model, engine_type, year, autorepair_id, specialtion_id) VALUES
('XJ', 'Бензин', 2017, 10, 6),
('S-Class', 'Дизель', 2020, 10, 8);















SELECT * from clients
-------------------------------------------------
--Test Statistic
 SELECT
                s.name AS service_name,
                COUNT(vs.visit_service_id) AS times_ordered,
                SUM(ars.service_price) AS total_revenue,
				A.name "Назва автомайстерні",
				A.adress,
				A.phone,
				A.EMAIL
            FROM Services s
                     JOIN Visit_Services vs ON s.service_id = vs.service_id
                     JOIN Visits v ON vs.visit_id = v.visit_id
                     JOIN Autorepair_Services ars ON s.service_id = ars.service_id AND v.autorepair_id = ars.autorepair_id
					 JOIN Autorepairs A ON A.AUTOREPAIR_ID = v.autorepair_id
            --WHERE v.autorepair_id = 2
              AND v.is_completed = TRUE
            GROUP BY s.name, A.name,
				A.adress,
				A.phone,
				A.EMAIL
            ORDER BY total_revenue DESC
                LIMIT 5;



-- 1. Додамо кількох клієнтів
INSERT INTO Clients (name, surname, email, phone) VALUES
('Олександр', 'Петренко', 'alex@gmail.com', '+380509998877'),
('Марія', 'Ковальчук', 'maria@ukr.net', '+380671112233'),
('Дмитро', 'Бондар', 'dimon@test.com', '+380935554433');

-- 2. Додамо їх автомобілі
-- (client_id 1, 2, 3 генеруються автоматично)
INSERT INTO Cars (brand, model, year, license_plate, vin, client_id) VALUES
('Toyota', 'Camry', 2018, 'AA1234AA', 'VIN1234567890', 1),
('Suzuki', 'Vitara', 2020, 'BC5678BC', 'VIN0987654321', 2),
('BMW', 'X5', 2015, 'KA9999KA', 'VIN1122334455', 3);

-- 3. Додамо ВІЗИТИ до AutoMaster Київ (autorepair_id = 1)
-- Важливо: ставимо is_completed = TRUE, бо ваш запит фільтрує саме такі візити
INSERT INTO Visits (date_time, car_id, autorepair_id, is_completed, payment_status) VALUES
('2025-10-01 10:00:00', 1, 1, TRUE, 'оплачено'), -- Візит 1 (Toyota)
('2025-10-02 14:00:00', 2, 1, TRUE, 'оплачено'), -- Візит 2 (Suzuki)
('2025-10-03 09:00:00', 3, 1, TRUE, 'оплачено'), -- Візит 3 (BMW)
('2025-10-05 11:00:00', 1, 1, FALSE, 'не оплачено'); -- Цей візит НЕ потрапить у статистику (не завершений)

-- 4. Додамо ПОСЛУГИ, виконані під час цих візитів (Visit_Services)
-- Вибираємо тільки ті послуги, які надає СТО №1 (id: 1, 3, 4, 5, 9, 11)

-- Для Візиту 1 (Toyota): Ремонт амортизаторів (дорога послуга) + Діагностика
INSERT INTO Visit_Services (visit_id, autorepair_service_id, problem_description) VALUES
(1, 5, 'Стук у підвісці'), -- id 5: Ремонт амортизаторів (2200 грн)
(1, 1, 'Перевірка помилок'); -- id 1: Компʼютерна діагностика (600 грн)

-- Для Візиту 2 (Suzuki): Тільки діагностика
INSERT INTO Visit_Services (visit_id, autorepair_service_id, problem_description) VALUES
(2, 1, 'Планова перевірка'); -- id 1: Компʼютерна діагностика (600 грн)

-- Для Візиту 3 (BMW): Заміна масла + Монтаж шин
INSERT INTO Visit_Services (visit_id, autorepair_service_id, problem_description) VALUES
(3, 3, 'Заміна мастила'), -- id 3: Заміна масла (950 грн)
(3, 11, 'Зміна гуми на зимову'); -- id 11: Монтаж шин (500 грн)


-- ================================================================
-- КРОК 1: Додаємо нових Клієнтів (для Дніпра та Полтави)
-- ================================================================
INSERT INTO Clients (name, surname, email, phone) VALUES
('Василь', 'Коваленко', 'vasya@dp.ua', '+380501111111'),   -- id буде 4
('Ірина', 'Мельник', 'ira@poltava.net', '+380672222222'),  -- id буде 5
('Олег', 'Сидоренко', 'oleg_boss@ukr.net', '+380933333333'); -- id буде 6

-- ================================================================
-- КРОК 2: Додаємо Автомобілі для цих клієнтів
-- ================================================================
-- Авто для Василя (Дніпро)
INSERT INTO Cars (brand, model, year, license_plate, vin, client_id) VALUES
('Mercedes-Benz', 'E-Class', 2016, 'AE0001AE', 'WDB12345678901234', 4),
('Volkswagen', 'Passat', 2019, 'AE7777CB', 'WVW22334455667788', 4);

-- Авто для Ірини (Полтава)
INSERT INTO Cars (brand, model, year, license_plate, vin, client_id) VALUES
('Ford', 'Fiesta', 2015, 'BI5678BI', 'WF099887766554433', 5);

-- Авто для Олега (Дніпро/Полтава - транзит)
INSERT INTO Cars (brand, model, year, license_plate, vin, client_id) VALUES
('Toyota', 'Land Cruiser', 2021, 'BI0007XX', 'JTE11223344556677', 6);

-- ================================================================
-- КРОК 3: Дані для TechGarage Дніпро (ID = 4)
-- Сценарій: Дорогі ремонти (високий середній чек)
-- ================================================================

-- 3.1. Візити (Completed = TRUE)
INSERT INTO Visits (date_time, car_id, autorepair_id, is_completed, payment_status, note) VALUES
('2025-10-10 09:00:00', 4, 4, TRUE, 'оплачено', 'Капіталка двигуна'),       -- Mercedes
('2025-10-12 11:30:00', 5, 4, TRUE, 'оплачено', 'Проблеми з коробкою'),     -- VW Passat
('2025-10-14 15:00:00', 4, 4, TRUE, 'оплачено', 'Планова діагностика');     -- Mercedes (повторно)

-- 3.2. Послуги (TechGarage надає: 1, 2, 7, 8, 9, 13, 15)
-- Див. ваші INSERT INTO Autorepair_Services для ID 4

-- Для візиту Mercedes (Капіталка)
INSERT INTO Visit_Services (visit_id, service_id, problem_description) VALUES
((SELECT MAX(visit_id) - 2 FROM Visits), 7, 'Капітальний ремонт двигуна (4800 грн)'); 

-- Для візиту VW Passat (КПП + Зчеплення)
INSERT INTO Visit_Services (visit_id, service_id, problem_description) VALUES
((SELECT MAX(visit_id) - 1 FROM Visits), 13, 'Ремонт коробки передач (5200 грн)'),
((SELECT MAX(visit_id) - 1 FROM Visits), 15, 'Заміна масла в КПП (1100 грн)');

-- Для другого візиту Mercedes (Діагностика)
INSERT INTO Visit_Services (visit_id, service_id, problem_description) VALUES
((SELECT MAX(visit_id) FROM Visits), 1, 'Компʼютерна діагностика (620 грн)');

-- ================================================================
-- КРОК 4: Дані для PitStop Полтава (ID = 6)
-- Сценарій: Швидкий сервіс (багато записів, малі суми)
-- ================================================================

-- 4.1. Візити
INSERT INTO Visits (date_time, car_id, autorepair_id, is_completed, payment_status) VALUES
('2025-10-15 10:00:00', 6, 6, TRUE, 'оплачено'), -- Ford Fiesta
('2025-10-15 12:00:00', 7, 6, TRUE, 'оплачено'), -- Toyota Land Cruiser
('2025-10-16 09:00:00', 6, 6, TRUE, 'оплачено'); -- Ford Fiesta (знову)

-- 4.2. Послуги (PitStop надає: 3, 4, 11, 12)

-- Ford (Масло + Фільтри)
INSERT INTO Visit_Services (visit_id, service_id, problem_description) VALUES
((SELECT MAX(visit_id) - 2 FROM Visits), 3, 'Заміна масла та фільтрів');

-- Toyota (Шиномонтаж)
INSERT INTO Visit_Services (visit_id, service_id, problem_description) VALUES
((SELECT MAX(visit_id) - 1 FROM Visits), 11, 'Монтаж та балансування шин');

-- Ford (Прокол колеса)
INSERT INTO Visit_Services (visit_id, service_id, problem_description) VALUES
((SELECT MAX(visit_id) FROM Visits), 12, 'Ремонт проколу шини');


----------------------------------------------------


SELECT A.autorepair_id, ARRAY_AGG(day_of_week) FROM Schedule_Workings SW
LEFT JOIN Autorepairs A ON A.autorepair_id = SW.autorepair_id
GROUP BY A.autorepair_id


SELECT tas.autorepair_service_id,
        s.name,
        s.description,
        TAS.service_price,
        TAS.garantie_term,
        TAS.duration,
        Cs.category_name FROM SERVICES S
LEFT JOIN Autorepair_Services TAS ON S.service_id = TAS.service_id
LEFT JOIN Category_Services CS ON CS.category_service_id = S.category_services_id


select * from cars;
select * from visits;
select * from clients;
select * from visit_services;







----------------------------------------------------------


SELECT 
    a.name AS назва,
    a.description AS опис,
    (
        SELECT COUNT(DISTINCT sa.specialtion_id)
        FROM Specialization_Autorepairs sa
        WHERE sa.autorepair_id = a.autorepair_id
    ) AS кількість_спеціалізацій,
    (
        SELECT COUNT(DISTINCT ars.service_id)
        FROM Autorepair_Services ars
        WHERE ars.autorepair_id = a.autorepair_id
    ) AS кількість_послуг,
    a.adress AS адрес,
    a.workers_amount AS кількість_співробітників,
    a.phone AS номер_телефону,
    a.email,
    a.ranking AS рейтинг,
    (
        SELECT AVG(ars.service_price)
        FROM Autorepair_Services ars
        WHERE ars.autorepair_id = a.autorepair_id
    ) AS середня_ціна_послуг,
    (
        SELECT COUNT(DISTINCT sw.day_of_week)
        FROM Schedule_Workings sw
        WHERE sw.autorepair_id = a.autorepair_id
    ) AS кількість_робочих_днів,
    (
        SELECT AVG(
            EXTRACT(HOUR FROM (sw.end_time_working - sw.start_time_working)) * 60 +
            EXTRACT(MINUTE FROM (sw.end_time_working - sw.start_time_working))
        ) / 60.0
        FROM Schedule_Workings sw
        WHERE sw.autorepair_id = a.autorepair_id
    ) AS середня_тривалість_робочого_дня,
    (
        SELECT COUNT(*)
        FROM Visits v
        WHERE v.autorepair_id = a.autorepair_id
        AND v.date_time <= CURRENT_DATE - 7
    ) AS візитів_за_тиждень,
    (
        SELECT COUNT(*)
        FROM Visits v
        WHERE v.autorepair_id = a.autorepair_id
        AND v.date_time <= CURRENT_DATE - 30
    ) AS візитів_за_місяць,
    (
        SELECT COUNT(*)
        FROM Visits v
        WHERE v.autorepair_id = a.autorepair_id
        AND v.date_time <= CURRENT_DATE - 365
    ) AS візитів_за_рік
FROM Autorepairs a
ORDER BY a.name;



SELECT 
DISTINCT
    s.name AS назва_послуги,
    s.description AS опис_послуги,
    (
        SELECT MIN(ars2.service_price)
        FROM Autorepair_Services ars2
        WHERE ars2.service_id = s.service_id
    ) AS мінімальна_ціна,
    (
        SELECT AVG(ars3.service_price)
        FROM Autorepair_Services ars3
        WHERE ars3.service_id = s.service_id
    ) AS середня_ціна,
    a.name AS назва_автомайстерні,
    ars.service_price AS базова_вартість,
    ars.garantie_term AS гарантійний_термін,
    ars.duration AS тривалість,
    a.phone AS телефон_автомайстерні,
    a.email AS email_автомайстерні
FROM Services s
LEFT JOIN Autorepair_Services ars ON s.service_id = ars.service_id
LEFT JOIN Autorepairs a ON ars.autorepair_id = a.autorepair_id
ORDER BY s.name, a.name;

