
export const DATABASE_CONNECTION_TOKEN = process.env.DATABASE_CONNECTION_NAME || 'PG_CONNECTION';
export const DATABASE_MYSQL_CONNECTION_TOKEN = process.env.DATABASE_MYSQL_CONNECTION_TOKEN || 'MYSQL_CONNECTION';